version: "3.8"

# https://medium.com/@cleverti/how-to-setup-docker-for-a-symfony-project-26d304359592

services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "8201:80"
    volumes:
      - ./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public

  postgres:
    image: postgres:14.5-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: barcode
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data:
  var:
