services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "8201:80"
    volumes:
      - ./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
